version: '3'

services:
    php-fpm:
        build:
            context: ./php-fpm
        volumes:
            - ../www:/var/www

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../www:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm

    mariadb:
        image: mariadb:10.2
        ports:
            - 127.0.0.1:3301:3306 # change ip if required
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: moonshiner_db
            MYSQL_USER: moonshiner
            MYSQL_PASSWORD: moonshiner
